[package]
name = "rust-advent-of-code-2018"
version = "0.1.0"
authors = ["Mitchell Johnson <ehntoo@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.0"
itertools = "0.7"
bit-vec = "0.5.0"
